module.exports = Object.freeze({
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    MENU_SELECTED_ITEM: 'MENU_SELECTED_ITEM',
    MENU_SELECTED_ITEM_DESC: "MENU_SELECTED_ITEM_DESC",
    SLACK_USERID: "SLACK_USERID",
    SLACK_CHANNELID: "SLACK_CHANNELID",
    LOCKED: "LOCKED",
    UNLOCKED: "UNLOCKED",
});